# Generated by Django 4.1.2 on 2022-10-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TarefaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'ToDo'), (2, 'Feito')])),
            ],
        ),
    ]
