# Generated by Django 4.1.2 on 2022-10-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefamodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tarefamodel',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'A_Fazer'), (2, 'Feito')]),
        ),
    ]
